import rawPlants from '@/data/plants.json';

export type EvidenceStatus =
  | 'experimentally_demonstrated'
  | 'proposed'
  | 'hypothesized'
  | 'not_established';

export type Plant = {
  slug: string;
  commonName: string;
  scientificName: string;
  family: string;
  location: string;
  photo?: string;
  latitude?: number;
  longitude?: number;
  traditionalUse: {
    en: string;
    hi: string;
    sa: string;
  };
  // Real research evidence, sourced from published literature — see
  // docs for how these are added. Absent when no verified literature
  // has been found yet.
  research?: {
    evidenceNote: string;
    evidenceStatus: EvidenceStatus;
    evidenceModel: string;
    citation: {
      authors: string;
      year: number | null;
      journal: string;
      title: string;
      doi?: string;
      pmid?: string;
    };
  };
};

type RawPlant = {
  slug: string;
  commonName: string;
  scientificName: string;
  family: string;
  location: string;
  photo?: string;
  latitude?: number;
  longitude?: number;
  traditionalUseEn: string;
  traditionalUseHi: string;
  traditionalUseSa: string;
  evidenceNote?: string;
  evidenceStatus?: EvidenceStatus;
  evidenceModel?: string;
  citationAuthors?: string;
  citationYear?: number | null;
  citationJournal?: string;
  citationTitle?: string;
  citationDoi?: string;
  citationPmid?: string;
};

// The real source of truth is data/plants.json — flat fields, so it maps
// cleanly to a spreadsheet's columns. This file just reshapes it into the
// nested shape the rest of the app expects. data/plants.json is normally
// regenerated by scripts/sync-plants.js from the Centre's Google Sheet —
// see docs/data-entry-guide.md.
export const plants: Plant[] = (rawPlants as RawPlant[]).map((p) => ({
  slug: p.slug,
  commonName: p.commonName,
  scientificName: p.scientificName,
  family: p.family,
  location: p.location,
  photo: p.photo || undefined,
  latitude: p.latitude,
  longitude: p.longitude,
  traditionalUse: {
    en: p.traditionalUseEn,
    hi: p.traditionalUseHi,
    sa: p.traditionalUseSa,
  },
  research: p.evidenceNote
    ? {
        evidenceNote: p.evidenceNote,
        evidenceStatus: p.evidenceStatus || 'proposed',
        evidenceModel: p.evidenceModel || '',
        citation: {
          authors: p.citationAuthors || '',
          year: p.citationYear ?? null,
          journal: p.citationJournal || '',
          title: p.citationTitle || '',
          doi: p.citationDoi || undefined,
          pmid: p.citationPmid || undefined,
        },
      }
    : undefined,
}));
