import rawPlants from '@/data/plants.json';

export type Plant = {
  slug: string;
  commonName: string;
  scientificName: string;
  family: string;
  location: string; // real, physical location on JNU campus
  // Path to a real photo, e.g. '/images/plants/opuntia-ficus-indica.jpg'.
  // Empty until a real photo exists — the page shows a clean placeholder
  // rather than a fabricated or stock image.
  photo?: string;
  traditionalUse: {
    en: string;
    hi: string;
    // AI-drafted — needs review by someone with Sanskrit training before
    // being treated as final, especially for modern biomedical terms
    // (blood sugar, cholesterol, antioxidant) that have no classical
    // Sanskrit equivalent and were rendered as best-effort approximations.
    sa: string;
  };
};

type RawPlant = {
  slug: string;
  commonName: string;
  scientificName: string;
  family: string;
  location: string;
  photo?: string;
  traditionalUseEn: string;
  traditionalUseHi: string;
  traditionalUseSa: string;
};

// The real source of truth is data/plants.json — flat fields, so it maps
// cleanly to a spreadsheet's columns. This file just reshapes it into the
// nested `traditionalUse: {en,hi,sa}` shape the rest of the app expects,
// so no component needs to know about the flat/spreadsheet format.
// data/plants.json is normally regenerated by scripts/sync-plants.js from
// the Centre's Google Sheet — see docs/data-entry-guide.md.
export const plants: Plant[] = (rawPlants as RawPlant[]).map((p) => ({
  slug: p.slug,
  commonName: p.commonName,
  scientificName: p.scientificName,
  family: p.family,
  location: p.location,
  photo: p.photo || undefined,
  traditionalUse: {
    en: p.traditionalUseEn,
    hi: p.traditionalUseHi,
    sa: p.traditionalUseSa,
  },
}));
